spring:
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8888/"
  application:
    name: API-GATEWAY

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

springdoc:
  swagger-ui:
    urls:
      - name: Eureka Server
        url: /gateway/eureka/v3/api-docs
      - name: Auth Service
        url: /gateway/auth/v3/api-docs
      - name: Application Service
        url: /gateway/applications/v3/api-docs
      - name: Document Service
        url: /gateway/documents/v3/api-docs
      - name: Admin Service
        url: /gateway/admin/v3/api-docs
