spring:
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888/"
  application:
    name: DOCUMENT-SERVICE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3037/document_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9090/eureka/}

document:
  dropbox:
    access-token: "sl.u.AGbw2cVK9YTZjRyHc3UFHClzKXijpmHvjj4_xiFFU1fjOLUJFSoSnQHaLHejcuqHZ3q_KVpdiMnyIVtR63PXVzQIrRnnbbbXPcE6iY99Aho6VlkHGoEan5HosacqOGzR4CJIDENSzvVeWCtyPfbBLd4cF7OzIXUOlRShK2VjCoe5kHq2k-9g8nbk0Iy3yNzWfi0Ot5m3zTYvNR6k0HHrafrBtpwS0LL2Ui8X-5hhjcroTD7i4S7F1rKEDsjkRA4NRSAsR2MMtHa4EcdD0k1cKFJWDs9nGmdd9PO-oAmGJ8ml-pGBGeaxEvuhVLFYkOsa-sM54hzNtEcXP4JFcbpHAT75ihxb7S_U_q_vN6ErxBLUgZkNhGNy7aYefHGqusMCf-NxY5mIpsy25y3Go6H98yry68WSLQZnRK7SwiFDxOAeMf8l3JkbBc4TOtt-6z28ZLBW-NkQobFifrJEpvQjyF7uEVGdPkVy5XZh2S0bT0Er2cKyV3MKu29E0NinLjEUF9Yr6nXv-iBtLS4oJ5pxZpZZ6RrLEYepJmqSvYWVVIBXzTmKAVyy7NiE_U17b9c2pEIejWlFQfH1fZrrBjm9fyLe6IEdhrrwNQSI8esXFhaE97y9ylwz50tW9-ll2fv781gxhrqvZXZxDCEG891J14QZKS_XbBIg6s4e2x6AUB_18opmPc5OJUCEJN7jlemZFoNK-yfRenigcDVL6b4kVFTW18nquItnXBpl6Vk0jVvsXfwjVYB8E8ZCXLL8eiU2WScm9TqzzygIEgYL9NymPKBtsJdbZ9uL7BM4Mmqz_DN5LmZlHjo45ZaJyKvzavfruQUn7uM5ThHy51E3_MXzaXyhfAaE3hWkRpzJMkZ-uBWUbAJBmCO9KQGsHxQbFj2V9CT22e765jg3y1I9fWQazoKN9HTp--0IMTFatDs8dzzDEvtVnIfkmDR_smMWkMRD5-pvm41jwZ-up4QcAnEiqfCtFQF9nIUVfiV5xjbNZBqsQ3xqq-db08DEb_R8Jwjc725bZX3IHl-Y8aVMrNS77hDfPkmD6MptAQC0h1yFoqhiUAfDj7M-rb7qj5uMJt2xODO3EhJLsxGw3ZGDr6tVcnUqrHSkE1aGshKHvEdHRsTDLyOBaAh-3JD_JQz4t7r9WuSqc2MZ32ny7ptU_m4TT6hwzKV4YXTXfVHcC32CBbZCSi1NddhomBwYlAYvrRRS9IOwG_mH7pgytMij8_sbzbmk_xGPgHIKBXbF0H6h631nyKcu4ABSi1Wx7WLUSTqnN3d6BdHHthEUCLTUuO_R3-kcnzr9UjIldgPZBOOgxrIBHCTvNu9lCM_5dQo7PAL90wVdy9_PiOobYPj9Cm_JhB8JbVCswmpPIvwhUGQ7QcL60q7_XFZjp-4Hjgks3f4meYomxPhm4rT_FZSk4RiXogRp0hQGWz2LoytDhsHBTvaAlRo1Co0J1GtF49gv1MrMEL8"
    folder: ${DOCUMENT_DROPBOX_FOLDER:/finflow}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
