spring:
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888/"
  application:
    name: DOCUMENT-SERVICE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3037/document_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:9090/eureka/}

document:
  dropbox:
    access-token: "sl.u.AGdj132SwpUlGcbs2ouXWd1vvpg_RHrTfVyAoEY_E1xQ_iy8WOsHcG8eSdRIEsEHFgS_wnTSRFcfFH7eV8YHaDQjj1L0dfPGTN4hAVGomxV01v75PDJ-fgp_WSSfKcHvpAiI7CHFUPRbl3olkvwOu28dULYeECJZq6L60ctJAIvTWiHk4YR_bD3Jn19U1b72H4Ne6NlzeQltRNtZ8KTXMkaTEr5ShpYPOv0MOVQGzUg4Va5aYkDCxlQ5_KYr28H-LjXVIyVarWu-xbbmNqAisG8yHTmvgbIoFrLnziSwPHIk4vwa3Dx-IkFY7tMItF48oXNPFLjplttOkeJu4Zy2WH9Ig7pYeWNxDTu1d5rH38KOkCt8purQV4f5TyAVdNaiI7KGn9NVJb0hECSZhDrN9765elxZpuz8euVJSLyTmCdRqVls2dt8oi41qZCBC0sx88RJz6fxJj7B3oQ4RfOgKxEQrrtzz-dLb82Qzfx9TLPZAgeBgp_bbmvrUmPWyVkOEWkkFQE5-A6oQV8OOdQkirCo-3VAKcaN4RCau1_muY6BGx0NUiR6d9E2qWsOqyqPDgV7Sb5OjvR0p8NYs2V_Gklwzbe9_ZzIsbso5lbsY13DUdImi2xA0GwHpKBqvlgIKyfn2soqSqNVreCyZSsOjZuR0VTQrxSqgpWa6tUCWJgPrAVfGcMkXw5BaTAI5z_5UTah4bqedUPLGUBDSO7HngAB551h3v1xj074RIG8Pc-udoEp9hSkI4E9eg_w5OEoNE1x4I8iASBnQreUuPmfAGYyFIv4DoMWUJXCvyd7MlzdkhGCmriENLXi9vPQJRCK7ZzdOC_9tKxC7qtlFK7tYeaHyl2OgINHHsopxtLzwQDhA1fLY5oWYyx_p9HYm1a5WzVhQt7JBGmkTMRHZg6fhtPZwhWqvAQycQdq-uUEqkgKxoAY3QS87R6-Afujyd_6E3HebqnFKJPcbn_ls3huWNdIbxxj4WzKmeSQuEQgNLQh63PxbeZpFTV8VeMd1YHBY1PlN7VVc9GCIgp5_UnpF5_5G_IIiXVw2ALBpCTB1CljyHk-Ol0nPztFbxCJBRlttoVV0Q0DXKQu2ZNXSrhvpeSsLo_2LJg1PalJ5gdncJba0ota-I5l905hb0vhUiKvkHCZiiDfd328xvVnydO1bJE79Q_Gt9V8xSznZ2BQWtvy4bSMipwrRw2_0PK4Lj4gRyA-JsA9RDfaggu5B8IsIvu5_Wr1mP9tWyne2L6c-hnj9FtBhNYauuJ3PiG0NuDPIcYBfrkFd5rpQ-2sDAYU6DpWrHBirvzLKEUFenJFGRXK2HalIrgInXsDfsmPh2Ip9EWpkZcw2nIZhIqi3pT3K3ppj5qFcw8UM6oC3zo88Nzvn8ArJDyRswLSZzdgAvbmzXNg9WMWFY14HgZqcnbwOyqpA4Z12RC02EsNQJeH1NCqcYRyZz75ysdi_mcrbaQ4WKk"
    folder: ${DOCUMENT_DROPBOX_FOLDER:/finflow}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

auth:
  jwt:
    secret: ${AUTH_JWT_SECRET:01234567890123456789012345678901}
